### ISSUE TITLE
Catch files opening with <control+p>

### ISSUE THREAD

**Issue by rexroni** [Enteleform/ST_ConditionalColorSchemes#1]
I love the plugin!

However, I've noticed when I use <control+p> to open a file in my project, it doesn't seem to call the on_load handler and I don't get my conditional color scheme.

Is there another listener that can be added to make this functionality work?

Thanks,

Ryan

**Comment by Enteleform** [comment]
@rexroni

Seems like it has something to do with ST's transient views and/or order of execution between `goto{onhighlight,ondone}` & `on_load`.

I added [**set_timeout_async**](https://github.com/Enteleform/ST_ConditionalColorSchemes/blob/master/ConditionalColorSchemes.py#L37-L38) around the `set("color_scheme", …)` command, and it seems to work for the case you described.

Just pushed the change in release 1.0.3, let me know if it works for you!

**Comment by rexroni** [comment]
Cool, thanks!  It's perfect!
